framework:
    messenger:
        # reset the default configuration
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: ~

        # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
        # failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async: 'doctrine://default?auto_setup=0'
            failed: 'doctrine://default?queue_name=failed&auto_setup=0'
            sync: 'sync://'

        routing:
            # Route your messages to the transports
            'Symfony\Component\Mailer\Messenger\SendEmailMessage': sync
            # 'Symfony\Component\Notifier\Message\ChatMessage': async
            # 'Symfony\Component\Notifier\Message\SmsMessage': async
